In [10]:
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd
import numpy as np



MovieUrl = 'http://www.imdb.com/chart/toptv'

response = requests.get(MovieUrl)
soup = BeautifulSoup(response.text, 'lxml')
IMDBS=pd.DataFrame()

In [8]:
MovieUrl = 'http://www.imdb.com/chart/toptv'

response = requests.get(MovieUrl)
soup = BeautifulSoup(response.text, 'lxml')
link_=soup.find_all(class_="titleColumn")
links_=[]
title=[]

for id_ in link_:
    
    final_url=id_.find("a").get("href") 
    url="http://imdb.com" + final_url
    links_.append(url)

links_

for i in links_:

    headers = {"Accept-Language": "en-US,en;q=0.5"}
    response1 = requests.get(i, headers=headers)
    soup1 = BeautifulSoup(response1.text, 'html.parser')

    title_=soup1.find("div", class_="sc-80d4314-1 fbQftq").h1.get_text()



    print(title_)
    title.append(title_)

Planet Earth II
Breaking Bad
Planet Earth
Band of Brothers
Chernobyl
The Wire
Blue Planet II
Avatar: The Last Airbender
Cosmos: A Spacetime Odyssey
The Sopranos
Cosmos
Our Planet
Game of Thrones
Rick and Morty
The World at War
Fullmetal Alchemist: Brotherhood
The Last Dance
Life
Sherlock
The Twilight Zone
The Vietnam War
Batman: The Animated Series
Scam 1992: The Harshad Mehta Story
Arcane
The Blue Planet
Attack on Titan
The Office
Firefly
Human Planet
Frozen Planet
Death Note
Only Fools and Horses
Hunter x Hunter
The Civil War
True Detective
Seinfeld
The Beatles: Get Back
Persona
Better Call Saul
Dekalog
Fargo
Clarkson's Farm
Cowboy Bebop
Nathan for You
Gravity Falls
When They See Us
Last Week Tonight with John Oliver
Friends
TVF Pitchers
Africa
Apocalypse: The Second World War
Monty Python's Flying Circus
It's Always Sunny in Philadelphia
Taskmaster
Das Boot
Curb Your Enthusiasm
The West Wing
Leyla and Mecnun
Pride and Prejudice
Fawlty Towers
Freaks and Geeks
Blackadder Goes Forth
Twin Peaks
Black Mirror
Narcos
BoJack Horseman
Succession
Chappelle's Show
Dragon Ball Z
Dragon Ball Z
I, Claudius
One Piece
South Park
As If
Rome
Peaky Blinders
Six Feet Under
Oz
Ted Lasso
Over the Garden Wall
Kota Factory
Dark
The Mandalorian
Steins;Gate
Arrested Development
The Boys
One Punch Man
The Simpsons
House
The Shield
Fleabag
Battlestar Galactica
Sarabhai V/S Sarabhai
Stranger Things
Downton Abbey
Gullak
Invincible
Mad Men
Panchayat
Vinland Saga
Peep Show
The Marvelous Mrs. Maisel
Severance
House of Cards
Star Trek: The Next Generation
The Adventures of Sherlock Holmes
The Crown
Friday Night Lights
Top Gear
The Grand Tour
Berserk
The Thick of It
1883
Justice League Unlimited
Line of Duty
Mahabharat
Deadwood
Dexter
The X-Files
Parks and Recreation
Father Ted
Aspirants
The Jinx: The Life and Deaths of Robert Durst
This Is Us
Naruto: Shippûden
Behzat Ç.: Bir Ankara Polisiyesi
Blackadder II
Code Geass
The Bridge
Heartstopper
Primal
Atlanta
The Rehearsal
Daredevil
Demon Slayer: Kimetsu no Yaiba
It's a Sin
Archer
Mystery Science Theater 3000
Yeh Meri Family
Young Justice
Critical Role
Gomorrah
Ramayan
Blackadder the Third
Lonesome Dove
Monster
The Return of Sherlock Holmes
Adventure Time
Yellowstone
Mindhunter
Haikyu!!
QI
Anne with an E
Mr. Bean
Dopesick
Making a Murderer
Yes Minister
Poirot
The Eric Andre Show
Justified
Boardwalk Empire
The Haunting of Hill House
The Newsroom
The Bugs Bunny Show
The Queen's Gambit
Formula 1: Drive to Survive
Impractical Jokers
Pose
Flight of the Conchords
Dragon Ball
Crash Landing on You
Justice League
Coupling
Dragon Ball
The Venture Bros.
Spaced
The Offer
Homicide: Life on the Street
Battlestar Galactica
Long Way Round
The Bureau
Black Sun
The Family Man
What We Do in the Shadows
Yes, Prime Minister
The IT Crowd
Samurai Champloo
Louie
Westworld
I'm Alan Partridge
The Office
Mr. Robot
Letterkenny
Through the Wormhole
Whose Line Is It Anyway?
House of the Dragon
Shameless
Samurai Jack
Spartacus
Brass Eye
Ezel
Extraordinary Attorney Woo
Skam
Doctor Who
North & South
Sons of Anarchy
Fullmetal Alchemist
Neon Genesis Evangelion
Jujutsu Kaisen
Silicon Valley
Detectorists
Endeavour
From the Earth to the Moon
Trailer Park Boys
Twin Peaks
Spartacus: Gods of the Arena
Mob Psycho 100
Rurouni Kenshin: Trust and Betrayal
Futurama
Cobra Kai
Umbre
Hannibal
Community
Schitt's Creek
The Expanse
Chef's Table
Generation Kill
The Angry Video Game Nerd
Regular Show
Mr Inbetween
The Night Of
My Brilliant Friend
Wentworth
Alfred Hitchcock Presents
Big Little Lies
The Great British Baking Show
Your Lie in April
The Knick
Content Cop
Southland
Queer Eye
Avrupa Yakasi
Black Books
John Adams
X-Men: The Animated Series
The Defiant Ones
Garth Marenghi's Darkplace
The Punisher
Foyle's War
SPY×FAMILY

In [12]:
IMDBS["title"]=title
IMDBS

                          title
0               Planet Earth II
1                  Breaking Bad
2                  Planet Earth
3              Band of Brothers
4                     Chernobyl
..                          ...
245            The Defiant Ones
246  Garth Marenghi's Darkplace
247                The Punisher
248                 Foyle's War
249                  SPY×FAMILY

[250 rows x 1 columns]

In [13]:
ratings=soup.find_all(class_="posterColumn")
rates_=[]

for indexa in ratings:

    rate=round(float(indexa.find("span", attrs={"name":"ir"})["data-value"]),2)
    rates_.append(rate)


IMDBS["Rates"]=rates_
IMDBS

                          title  Rates
0               Planet Earth II   9.44
1                  Breaking Bad   9.43
2                  Planet Earth   9.42
3              Band of Brothers   9.39
4                     Chernobyl   9.32
..                          ...    ...
245            The Defiant Ones   8.42
246  Garth Marenghi's Darkplace   8.41
247                The Punisher   8.41
248                 Foyle's War   8.41
249                  SPY×FAMILY   8.41

[250 rows x 2 columns]

In [14]:
ratings=soup.find_all(class_="ratingColumn imdbRating")
nvotes=[]
for index in ratings:

    votes=index.find("strong").get("title").split("on")[1].split(" ")[1].replace(",","")
    nvotes.append(int(votes))


nvotes

IMDBS["NVotes"]=nvotes

IMDBS

                          title  Rates   NVotes
0               Planet Earth II   9.44   144196
1                  Breaking Bad   9.43  1849373
2                  Planet Earth   9.42   209100
3              Band of Brothers   9.39   464282
4                     Chernobyl   9.32   739569
..                          ...    ...      ...
245            The Defiant Ones   8.42    14792
246  Garth Marenghi's Darkplace   8.41    18576
247                The Punisher   8.41   233733
248                 Foyle's War   8.41    15628
249                  SPY×FAMILY   8.41    21701

[250 rows x 3 columns]

In [15]:
IMDBS.to_csv("IMDBS", sep='\t')